[package]
name = "ScallopReferralProgram"
version = "0.0.1"
published-at = "0x709ce9b97a63c6815c385ffd31c354dcd8f760984610581be23b838af4c6f60b"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "mainnet"
override = true

[dependencies.ScallopProtocol]
git = "https://github.com/scallop-io/sui-lending-protocol.git"
subdir = "contracts/protocol"
rev = "mainnet-v1.6"

[dependencies.VeSca]
git = "https://github.com/scallop-io/ve-sca-interface.git"
rev = "main"

[addresses]
scallop_referral_program = "0x0"
